"""Enhanced state models for the InfraAgent ReAct orchestrator.

Defines Pydantic v2 models for multi-intent classification, execution
planning, reasoning traces, approval workflows, and runbook execution.
All models are backward-compatible with the original InfraState fields.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from operator import add
from typing import Annotated, Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Reasoning trace
# ---------------------------------------------------------------------------


class ReasoningStep(BaseModel):
    """Single step in the agent's reasoning trace."""

    step_number: int = 0
    thought: str = ""
    action: str = ""
    action_input: dict[str, Any] = {}
    observation: str = ""
    status: str = "pending"  # pending | success | error | skipped | pending_approval
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    duration_ms: int = 0


# ---------------------------------------------------------------------------
# Intent classification
# ---------------------------------------------------------------------------


class IntentClassification(BaseModel):
    """Multi-intent classification result with confidence scores."""

    intents: list[str] = []
    confidence: dict[str, float] = {}
    primary_intent: str = "unknown"
    requires_multi_agent: bool = False
    reasoning: str = ""


# ---------------------------------------------------------------------------
# Execution planning
# ---------------------------------------------------------------------------


class PlannedStep(BaseModel):
    """A single planned step before execution."""

    step_number: int = 0
    description: str = ""
    tool_name: str = ""
    tool_args: dict[str, Any] = {}
    depends_on: list[int] = []
    is_destructive: bool = False
    is_conditional: bool = False
    condition: str = ""


class ExecutionPlan(BaseModel):
    """Structured plan generated by the planner."""

    plan_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    steps: list[PlannedStep] = []
    estimated_tool_calls: int = 0
    requires_approval: bool = False
    approval_step_indices: list[int] = []


# ---------------------------------------------------------------------------
# Approval workflow
# ---------------------------------------------------------------------------


class ApprovalRequest(BaseModel):
    """Request for human approval before a destructive action."""

    request_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    action_description: str = ""
    tool_name: str = ""
    tool_args: dict[str, Any] = {}
    risk_level: str = "medium"  # low | medium | high | critical
    status: str = "pending"  # pending | approved | rejected | timed_out
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    resolved_at: datetime | None = None
    rejection_reason: str = ""


# ---------------------------------------------------------------------------
# Orchestrator state
# ---------------------------------------------------------------------------


class InfraState(BaseModel):
    """Enhanced orchestrator state — backward-compatible with v1.

    New fields power the ReAct engine, multi-intent classification,
    conversation memory, and approval workflows.  The original
    ``k8s_data``, ``gpu_data``, ``incident_data``, and ``intent``
    fields are preserved for backward compatibility.
    """

    # --- Query & context ---
    query: str = ""
    thread_id: str = "default"
    conversation_history: Annotated[list[dict[str, Any]], add] = []

    # --- Classification ---
    classification: IntentClassification | None = None
    intent: str = ""  # backward compat — set from primary_intent

    # --- Planning ---
    execution_plan: ExecutionPlan | None = None
    current_step: int = 0

    # --- Reasoning trace (visible to user) ---
    reasoning_trace: Annotated[list[ReasoningStep], add] = []

    # --- Domain data (backward compat) ---
    k8s_data: dict[str, Any] = {}
    gpu_data: dict[str, Any] = {}
    incident_data: dict[str, Any] = {}

    # --- Unified tool results (new) ---
    tool_results: Annotated[list[dict[str, Any]], add] = []

    # --- Approval workflow ---
    pending_approvals: list[ApprovalRequest] = []
    approval_responses: dict[str, str] = {}

    # --- Runbook context ---
    active_runbook: dict[str, Any] | None = None
    runbook_step: int = 0

    # --- Output ---
    response: str = ""
    actions_taken: Annotated[list[str], add] = []
    iteration_count: int = 0
    max_iterations: int = 15
